<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Features\Auth\" />
    <Folder Include="Features\DeliveryAdmins\" />
    <Folder Include="Features\DeliveryProofs\" />
    <Folder Include="Features\DriverLocationPings\" />
    <Folder Include="Features\GeoZones\" />
    <Folder Include="Features\BulkUploadBatch\" />
    <Folder Include="Features\OrderDriverAssignment\Queries\GetPendingOffers\" />
    <Folder Include="Features\OrderDriverAssignment\Queries\GetExpiredOffers\" />
    <Folder Include="Features\OrderDriverAssignment\Queries\GetDriverOffer\" />
    <Folder Include="Features\Return\" />
    <Folder Include="Features\NoitificationLogs\Commands\LogNotification\" />
    <Folder Include="Features\NoitificationLogs\Queries\" />
    <Folder Include="Features\OrderStatusHistories\" />
    <Folder Include="Features\Orders\Command\BulkUpload\" />
    <Folder Include="Features\Roles\Command\CreateRole\" />
    <Folder Include="Features\Roles\Queries\GetRoleDetails\" />
    <Folder Include="Features\Roles\Queries\GetAllRoles\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HaitikBackend.Domain\HaitikBackend.Domain.csproj" />
  </ItemGroup>

</Project>
